### PR TITLE
close both conns on error

### PR DESCRIPTION
**Pull request by jmhodges**

### CODE REVIEW

**Comment by jsha** [comment]
This only handles one connection at a time now. I think you need to add a `go handleConnection`.

Also, this still prints errors when one side of the connection closes.

**Comment by jmhodges** [comment]
Oh, sorry, I thought the Accept loop was the usual go-ing one. Fixing.

Didn't think the printing of errors was the problem, just the not closing correctly. Can fix that, too.

**Comment by jmhodges** [comment]
There we go

**Comment by jmhodges** [comment]
Nevermind, this PR is bad.

**Pull request closed without merging**
